apply plugin: 'java'
apply plugin: 'org.jetbrains.kotlin.jvm'
apply plugin: 'application'
apply plugin: 'com.joom.colonist'

java {
  sourceCompatibility = javaVersion
  targetCompatibility = javaVersion
}

application {
  mainClass = 'com.joom.colonist.modular.ColonistSampleKt'
}

kotlin {
  compilerOptions {
    jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_11
  }
}

dependencies {
  implementation "org.jetbrains.kotlin:kotlin-stdlib$kotlinRuntimeVariant:$kotlinVersion"

  testImplementation "junit:junit:$junitVersion"
}

tasks.named('jar', Jar).configure {
  destinationDirectory.set(file('build/jar'))

  from {
    configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
  }

  duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

colonist {
  processTest false
  discoverSettlers true
}
