buildscript {
  apply from: 'versions.gradle'

  repositories {
    mavenLocal()
    google()
    mavenCentral()
    gradlePluginPortal()
  }

  dependencies {
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
    classpath "com.android.tools.build:gradle:$androidToolsVersion"
    classpath "com.joom.colonist:colonist-gradle-plugin:$COLONIST_VERSION"
  }
}

plugins {
  id "org.jlleitschuh.gradle.ktlint" version "10.2.1"
}

allprojects {
  version = COLONIST_VERSION
  group = COLONIST_GROUP

  buildscript {
    repositories {
      mavenLocal()
      google()
      mavenCentral()
      gradlePluginPortal()
    }
  }

  repositories {
    mavenLocal()
    google()
    mavenCentral()
  }

  apply plugin: "org.jlleitschuh.gradle.ktlint"

  tasks.withType(Test).configureEach {
    failOnNoDiscoveredTests = false
  }

  gradle.projectsEvaluated {
    tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
      compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_11
        apiVersion = org.jetbrains.kotlin.gradle.dsl.KotlinVersion.fromVersion(kotlinLanguageVersion)
        languageVersion = org.jetbrains.kotlin.gradle.dsl.KotlinVersion.fromVersion(kotlinLanguageVersion)
        allWarningsAsErrors = true
      }
    }
  }
}
