apply plugin: 'java-library'
apply from: "$rootDir/publish.gradle"

java {
  sourceCompatibility = javaVersion
  targetCompatibility = javaVersion
}

mavenPublishing {
  coordinates(project.group.toString(), 'colonist-core', project.version.toString())
}

dependencies {
  api project(":annotations")
  implementation "com.google.code.findbugs:jsr305:$jsr305Version"

  testImplementation "junit:junit:$junitVersion"
  testImplementation "com.google.code.findbugs:jsr305:$jsr305Version"
}
