apply plugin: 'com.android.application'
apply plugin: 'org.jetbrains.kotlin.android'
apply plugin: 'com.joom.colonist.android'

def enabledFeatures = project.properties['enabledFeatures']?.toString() ?: ''

android {
  namespace 'com.joom.colonist.modular'
  compileSdk androidCompileSdkVersion

  buildFeatures {
    buildConfig = true
  }

  defaultConfig {
    applicationId 'com.joom.colonist.modular'
    minSdkVersion androidMinSdkVersion
    targetSdkVersion androidTargetSdkVersion
    versionCode 1
    versionName version

    buildConfigField 'String', 'ENABLED_FEATURES', "\"$enabledFeatures\""

    testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
  }

  testOptions {
    unitTests {
      returnDefaultValues true
    }
  }

  compileOptions {
    sourceCompatibility javaVersion
    targetCompatibility javaVersion
  }
}

colonist {
  processTest = true
}

kotlin {
  compilerOptions {
    jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_11
  }
}

dependencies {
  implementation project(':colonist-samples:modular-android:modular-colony')
  for (feature in enabledFeatures.tokenize(',')) {
    implementation project(":colonist-samples:modular-android:modular-$feature")
  }

  implementation "org.jetbrains.kotlin:kotlin-stdlib$kotlinRuntimeVariant:$kotlinVersion"

  testImplementation "junit:junit:$junitVersion"

  androidTestImplementation project(':colonist-samples:modular-android:modular-colony')
  androidTestImplementation "androidx.test.espresso:espresso-core:$androidxEspressoVersion"
  androidTestImplementation "androidx.test:rules:$androidxTestRulesVersion"
  androidTestImplementation "androidx.test:runner:$androidxTestRunnerVersion"
  androidTestImplementation "androidx.test.ext:junit:$androidxTestExtJunitVersion"
}
