buildscript {
  apply from: '../versions.gradle'

  repositories {
    mavenLocal()
    google()
    mavenCentral()
    gradlePluginPortal()
  }

  dependencies {
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
    classpath "com.android.tools.build:gradle:$androidToolsVersion"
    classpath "com.vanniktech:gradle-maven-publish-plugin:$mavenPublishVersion"
    classpath "com.gradleup.shadow:shadow-gradle-plugin:$shadowVersion"
  }
}

plugins {
  id "org.jlleitschuh.gradle.ktlint" version "10.2.1"
}

allprojects {
  version = COLONIST_VERSION
  group = COLONIST_GROUP

  buildscript {
    repositories {
      mavenLocal()
      google()
      mavenCentral()
      gradlePluginPortal()
    }
  }

  repositories {
    mavenLocal()
    google()
    mavenCentral()
  }

  apply plugin: "org.jlleitschuh.gradle.ktlint"
}

apply plugin: 'org.jetbrains.kotlin.jvm'

sourceSets {
  functionalTest {
    java {
      compileClasspath += main.output
      runtimeClasspath += main.output
    }
  }
}

dependencies {
  functionalTestImplementation gradleTestKit()
  functionalTestImplementation "junit:junit:$junitVersion"
}

tasks.register("functionalTest", Test.class) {
  description = "Runs functional tests."
  group = "verification"

  testClassesDirs = project.sourceSets.functionalTest.output.classesDirs
  classpath = project.sourceSets.functionalTest.runtimeClasspath
}

afterEvaluate {
  tasks.named("functionalTest") {
    subprojects.each {
      dependsOn(it.tasks.named("publishToMavenLocal"))
    }
  }
}

def pluginTestJavaVersion = JavaVersion.VERSION_17

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
  compilerOptions {
    jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget(pluginTestJavaVersion.toString())
    apiVersion = org.jetbrains.kotlin.gradle.dsl.KotlinVersion.fromVersion(kotlinLanguageVersion)
    languageVersion = org.jetbrains.kotlin.gradle.dsl.KotlinVersion.fromVersion(kotlinLanguageVersion)
    allWarningsAsErrors = true
  }
}

tasks.withType(JavaCompile).configureEach {
  sourceCompatibility = pluginTestJavaVersion.toString()
  targetCompatibility = pluginTestJavaVersion.toString()
}
