apply plugin: 'java'
apply plugin: 'application'
apply plugin: 'com.joom.colonist'

java {
  sourceCompatibility = javaVersion
  targetCompatibility = javaVersion
}

application {
  mainClass = 'com.joom.colonist.modular.ColonistSample'
}

dependencies {
  testImplementation "junit:junit:$junitVersion"
}

tasks.named('jar', Jar).configure {
  destinationDirectory.set(file('build/jar'))

  from {
    configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
  }
}

colonist {
  processTest false
  discoverSettlers true
}
