import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import org.jlleitschuh.gradle.ktlint.tasks.BaseKtLintCheckTask

evaluationDependsOn(':processor')

apply plugin: 'java-library'
apply plugin: 'org.jetbrains.kotlin.jvm'
apply plugin: 'idea'
apply plugin: 'com.gradleup.shadow'
apply from: "$rootDir/publish.gradle"
apply from: "$rootDir/shadow-publish.gradle"

java {
  sourceCompatibility = javaVersion
  targetCompatibility = javaVersion
}

kotlin {
  compilerOptions {
    jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_11
    apiVersion = org.jetbrains.kotlin.gradle.dsl.KotlinVersion.fromVersion(kotlinLanguageVersion)
    languageVersion = org.jetbrains.kotlin.gradle.dsl.KotlinVersion.fromVersion(kotlinLanguageVersion)
  }
}

mavenPublishing {
  coordinates(project.group.toString(), 'colonist-gradle-plugin', project.version.toString())
}

shadow {
  addShadowVariantIntoJavaComponent = false
}

dependencies {
  implementation "org.jetbrains.kotlin:kotlin-stdlib$kotlinRuntimeVariant:$kotlinVersion"

  compileOnly project(':processor')
  compileOnly gradleApi()
  compileOnly "com.android.tools.build:gradle:$androidToolsVersion"
  compileOnly "com.android.tools.build:gradle-api:$androidToolsVersion"
}

afterEvaluate {
  def processorProject = project(':processor')
  def processorJar = processorProject.tasks.named('jar')
  def processorShadowJar = processorProject.tasks.named('shadowJar')

  tasks.named('shadowJar', com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar).configure {
    dependsOn(processorShadowJar, processorJar)
    configurations = [project.configurations.runtimeClasspath]
    dependencies {
      exclude(project(':processor'))
    }
    from(processorShadowJar.flatMap { it.archiveFile }.map { zipTree(it) })
  }
}

def generatedDir = new File(projectDir, "generated")
def generatedJavaSourcesDir = new File(generatedDir, "main/java")

def generateBuildClassTask = tasks.register('generateBuildClass') {
  inputs.property('version', version)
  outputs.dir generatedJavaSourcesDir

  doLast {
    def buildClassFile = new File(generatedJavaSourcesDir, "com/joom/colonist/plugin/Build.java")
    buildClassFile.parentFile.mkdirs()
    buildClassFile.text = "" +
        "package com.joom.colonist.plugin;\n" +
        "\n" +
        "public class Build {\n" +
        "    public static final String VERSION = \"$version\";\n" +
        "}\n"
  }
}

sourceSets {
  main {
    java.srcDirs += generatedJavaSourcesDir
    kotlin.srcDirs += generatedJavaSourcesDir
  }
}

tasks.matching { it instanceof AbstractCompile || it instanceof KotlinCompile || it instanceof BaseKtLintCheckTask }.configureEach {
  dependsOn generateBuildClassTask
}

project.afterEvaluate {
  tasks.named(sourceSets.main.getSourcesJarTaskName()).configure {
    dependsOn generateBuildClassTask
  }
}

clean.doFirst {
  delete generatedDir
}

idea {
  module {
    generatedSourceDirs += generatedJavaSourcesDir
  }
}
