apply plugin: 'java'
apply plugin: 'com.joom.colonist'

java {
  sourceCompatibility = javaVersion
  targetCompatibility = javaVersion
}

dependencies {
  implementation "com.joom.colonist:colonist-core:$version"
  implementation project(":colonist-samples:modular-java:modular-colony-api")
}

colonist {
  processTest false
  discoverSettlers true
}
